### ISSUE TITLE
Call db methods outside callback function

### ISSUE THREAD

**Issue by uetchy** [blahah/yunodb#10]
How can I call `db.add` or `db.search` outside yuno() callback function?

```js
const yuno = require('yunodb')

const dbopts = {
  location: './mydb',
  keyField: 'id',
  indexMap: ['full_name', 'description', 'readme']
}

const db = yuno(dbopts, (err, dbhandle) => {
  if (err) throw err
  db = dbhandle
})

const cursor = db.search(process.argv[2], (err, results) => {
  if (err) throw err

  console.log(results.totalHits);
  console.log(JSON.parse(results.hits[0].document).full_name);
})
```

Currently, yunodb throw this error:
```
/path/to/repo/node_modules/yunodb/cursor.js:50
  this.db.index.search(q, (err, results) => {
               ^

TypeError: Cannot read property 'search' of undefined
at Cursor.queryWithOffset (/path/to/repo/node_modules/yunodb/cursor.js:50:16)
at Cursor.first (/path/to/repo/node_modules/yunodb/cursor.js:18:15)
at Yuno.search (/path/to/repo/node_modules/yunodb/index.js:98:10)
at Object.<anonymous> (/path/to/repo/search.js:15:19)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
```

**Comment by blahah** [comment]
You need to wait for the db to be ready - we should probably have events for this, but right now it's just the callback.

So you could do something like...

```js
const yuno = require('yunodb')

const dbopts = {
  location: './mydb',
  keyField: 'id',
  indexMap: ['full_name', 'description', 'readme']
}

let db

const search = () => {
  const cursor = db.search(process.argv[2], (err, results) => {
    if (err) throw err 

    console.log(results.totalHits);
    console.log(JSON.parse(results.hits[0].document).full_name);
  })
}

yuno(dbopts, (err, dbhandle) => {
  if (err) throw err
  db = dbhandle
  search()
})
```

**Comment by uetchy** [comment]
Thank you for the example code. It's so helpful.
We probably need something like Promise other than callback methods.
Anyway, you can close this issue.
